//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
using System.Threading.Tasks;

namespace App19.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servis.cyanlog.com/EVAglobal6.asmx", ConfigurationName="ServiceReference1.EVAglobalSoap")]
    public interface EVAglobalSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servis.cyanlog.com/EVAglobal6.asmx/servistest", ReplyAction="*")]
        System.Threading.Tasks.Task<App19.ServiceReference1.servistestResponse> servistestAsync(App19.ServiceReference1.servistestRequest request);
        Task<konusResponse> konusAsync(string soru, string cyanid, string cyanpas, string p, string lng);
        [System.ServiceModel.OperationContractAttribute(Action="http://servis.cyanlog.com/EVAglobal6.asmx/login", ReplyAction="*")]
        System.Threading.Tasks.Task<App19.ServiceReference1.loginResponse> loginAsync(App19.ServiceReference1.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servis.cyanlog.com/EVAglobal6.asmx/konus", ReplyAction="*")]
        System.Threading.Tasks.Task<App19.ServiceReference1.konusResponse> konusAsync(App19.ServiceReference1.konusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servis.cyanlog.com/EVAglobal6.asmx/ai", ReplyAction="*")]
        System.Threading.Tasks.Task<App19.ServiceReference1.aiResponse> aiAsync(App19.ServiceReference1.aiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servis.cyanlog.com/EVAglobal6.asmx/bekci", ReplyAction="*")]
        System.Threading.Tasks.Task<App19.ServiceReference1.bekciResponse> bekciAsync(App19.ServiceReference1.bekciRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servis.cyanlog.com/EVAglobal6.asmx/userinfo", ReplyAction="*")]
        System.Threading.Tasks.Task<App19.ServiceReference1.userinfoResponse> userinfoAsync(App19.ServiceReference1.userinfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servis.cyanlog.com/EVAglobal6.asmx/goruntu", ReplyAction="*")]
        System.Threading.Tasks.Task<App19.ServiceReference1.goruntuResponse> goruntuAsync(App19.ServiceReference1.goruntuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servis.cyanlog.com/EVAglobal6.asmx/ucparti", ReplyAction="*")]
        System.Threading.Tasks.Task<App19.ServiceReference1.ucpartiResponse> ucpartiAsync(App19.ServiceReference1.ucpartiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servis.cyanlog.com/EVAglobal6.asmx/robotdata", ReplyAction="*")]
        System.Threading.Tasks.Task<App19.ServiceReference1.robotdataResponse> robotdataAsync(App19.ServiceReference1.robotdataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servis.cyanlog.com/EVAglobal6.asmx/classctrl", ReplyAction="*")]
        System.Threading.Tasks.Task<App19.ServiceReference1.classctrlResponse> classctrlAsync(App19.ServiceReference1.classctrlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class servistestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="servistest", Namespace="http://servis.cyanlog.com/EVAglobal6.asmx", Order=0)]
        public App19.ServiceReference1.servistestRequestBody Body;
        
        public servistestRequest() {
        }
        
        public servistestRequest(App19.ServiceReference1.servistestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class servistestRequestBody {
        
        public servistestRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class servistestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="servistestResponse", Namespace="http://servis.cyanlog.com/EVAglobal6.asmx", Order=0)]
        public App19.ServiceReference1.servistestResponseBody Body;
        
        public servistestResponse() {
        }
        
        public servistestResponse(App19.ServiceReference1.servistestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servis.cyanlog.com/EVAglobal6.asmx")]
    public partial class servistestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string servistestResult;
        
        public servistestResponseBody() {
        }
        
        public servistestResponseBody(string servistestResult) {
            this.servistestResult = servistestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://servis.cyanlog.com/EVAglobal6.asmx", Order=0)]
        public App19.ServiceReference1.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(App19.ServiceReference1.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servis.cyanlog.com/EVAglobal6.asmx")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cyanid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cyanpass;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(string cyanid, string cyanpass) {
            this.cyanid = cyanid;
            this.cyanpass = cyanpass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://servis.cyanlog.com/EVAglobal6.asmx", Order=0)]
        public App19.ServiceReference1.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(App19.ServiceReference1.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servis.cyanlog.com/EVAglobal6.asmx")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginResult;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(string loginResult) {
            this.loginResult = loginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class konusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="konus", Namespace="http://servis.cyanlog.com/EVAglobal6.asmx", Order=0)]
        public App19.ServiceReference1.konusRequestBody Body;
        
        public konusRequest() {
        }
        
        public konusRequest(App19.ServiceReference1.konusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servis.cyanlog.com/EVAglobal6.asmx")]
    public partial class konusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string soru;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cyanid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cyanpass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string p;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string lng;
        
        public konusRequestBody() {
        }
        
        public konusRequestBody(string soru, string cyanid, string cyanpass, string p, string lng) {
            this.soru = soru;
            this.cyanid = cyanid;
            this.cyanpass = cyanpass;
            this.p = p;
            this.lng = lng;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class konusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="konusResponse", Namespace="http://servis.cyanlog.com/EVAglobal6.asmx", Order=0)]
        public App19.ServiceReference1.konusResponseBody Body;
        
        public konusResponse() {
        }
        
        public konusResponse(App19.ServiceReference1.konusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servis.cyanlog.com/EVAglobal6.asmx")]
    public partial class konusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string konusResult;
        
        public konusResponseBody() {
        }
        
        public konusResponseBody(string konusResult) {
            this.konusResult = konusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class aiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ai", Namespace="http://servis.cyanlog.com/EVAglobal6.asmx", Order=0)]
        public App19.ServiceReference1.aiRequestBody Body;
        
        public aiRequest() {
        }
        
        public aiRequest(App19.ServiceReference1.aiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class aiRequestBody {
        
        public aiRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class aiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="aiResponse", Namespace="http://servis.cyanlog.com/EVAglobal6.asmx", Order=0)]
        public App19.ServiceReference1.aiResponseBody Body;
        
        public aiResponse() {
        }
        
        public aiResponse(App19.ServiceReference1.aiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servis.cyanlog.com/EVAglobal6.asmx")]
    public partial class aiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string aiResult;
        
        public aiResponseBody() {
        }
        
        public aiResponseBody(string aiResult) {
            this.aiResult = aiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bekciRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bekci", Namespace="http://servis.cyanlog.com/EVAglobal6.asmx", Order=0)]
        public App19.ServiceReference1.bekciRequestBody Body;
        
        public bekciRequest() {
        }
        
        public bekciRequest(App19.ServiceReference1.bekciRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servis.cyanlog.com/EVAglobal6.asmx")]
    public partial class bekciRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sor;
        
        public bekciRequestBody() {
        }
        
        public bekciRequestBody(string sor) {
            this.sor = sor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bekciResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bekciResponse", Namespace="http://servis.cyanlog.com/EVAglobal6.asmx", Order=0)]
        public App19.ServiceReference1.bekciResponseBody Body;
        
        public bekciResponse() {
        }
        
        public bekciResponse(App19.ServiceReference1.bekciResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servis.cyanlog.com/EVAglobal6.asmx")]
    public partial class bekciResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object bekciResult;
        
        public bekciResponseBody() {
        }
        
        public bekciResponseBody(object bekciResult) {
            this.bekciResult = bekciResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class userinfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="userinfo", Namespace="http://servis.cyanlog.com/EVAglobal6.asmx", Order=0)]
        public App19.ServiceReference1.userinfoRequestBody Body;
        
        public userinfoRequest() {
        }
        
        public userinfoRequest(App19.ServiceReference1.userinfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servis.cyanlog.com/EVAglobal6.asmx")]
    public partial class userinfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cyanid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cyanpass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string istek;
        
        public userinfoRequestBody() {
        }
        
        public userinfoRequestBody(string cyanid, string cyanpass, string istek) {
            this.cyanid = cyanid;
            this.cyanpass = cyanpass;
            this.istek = istek;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class userinfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="userinfoResponse", Namespace="http://servis.cyanlog.com/EVAglobal6.asmx", Order=0)]
        public App19.ServiceReference1.userinfoResponseBody Body;
        
        public userinfoResponse() {
        }
        
        public userinfoResponse(App19.ServiceReference1.userinfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servis.cyanlog.com/EVAglobal6.asmx")]
    public partial class userinfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object userinfoResult;
        
        public userinfoResponseBody() {
        }
        
        public userinfoResponseBody(object userinfoResult) {
            this.userinfoResult = userinfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class goruntuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="goruntu", Namespace="http://servis.cyanlog.com/EVAglobal6.asmx", Order=0)]
        public App19.ServiceReference1.goruntuRequestBody Body;
        
        public goruntuRequest() {
        }
        
        public goruntuRequest(App19.ServiceReference1.goruntuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servis.cyanlog.com/EVAglobal6.asmx")]
    public partial class goruntuRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cyanid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cyanpass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string p;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string lng;
        
        public goruntuRequestBody() {
        }
        
        public goruntuRequestBody(string name, string cyanid, string cyanpass, string p, string lng) {
            this.name = name;
            this.cyanid = cyanid;
            this.cyanpass = cyanpass;
            this.p = p;
            this.lng = lng;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class goruntuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="goruntuResponse", Namespace="http://servis.cyanlog.com/EVAglobal6.asmx", Order=0)]
        public App19.ServiceReference1.goruntuResponseBody Body;
        
        public goruntuResponse() {
        }
        
        public goruntuResponse(App19.ServiceReference1.goruntuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servis.cyanlog.com/EVAglobal6.asmx")]
    public partial class goruntuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string goruntuResult;
        
        public goruntuResponseBody() {
        }
        
        public goruntuResponseBody(string goruntuResult) {
            this.goruntuResult = goruntuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ucpartiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ucparti", Namespace="http://servis.cyanlog.com/EVAglobal6.asmx", Order=0)]
        public App19.ServiceReference1.ucpartiRequestBody Body;
        
        public ucpartiRequest() {
        }
        
        public ucpartiRequest(App19.ServiceReference1.ucpartiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servis.cyanlog.com/EVAglobal6.asmx")]
    public partial class ucpartiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cyankey;
        
        public ucpartiRequestBody() {
        }
        
        public ucpartiRequestBody(string id, string cyankey) {
            this.id = id;
            this.cyankey = cyankey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ucpartiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ucpartiResponse", Namespace="http://servis.cyanlog.com/EVAglobal6.asmx", Order=0)]
        public App19.ServiceReference1.ucpartiResponseBody Body;
        
        public ucpartiResponse() {
        }
        
        public ucpartiResponse(App19.ServiceReference1.ucpartiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servis.cyanlog.com/EVAglobal6.asmx")]
    public partial class ucpartiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ucpartiResult;
        
        public ucpartiResponseBody() {
        }
        
        public ucpartiResponseBody(string ucpartiResult) {
            this.ucpartiResult = ucpartiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class robotdataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="robotdata", Namespace="http://servis.cyanlog.com/EVAglobal6.asmx", Order=0)]
        public App19.ServiceReference1.robotdataRequestBody Body;
        
        public robotdataRequest() {
        }
        
        public robotdataRequest(App19.ServiceReference1.robotdataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servis.cyanlog.com/EVAglobal6.asmx")]
    public partial class robotdataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hareketistek;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cyanid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int unit;
        
        public robotdataRequestBody() {
        }
        
        public robotdataRequestBody(string hareketistek, string cyanid, int unit) {
            this.hareketistek = hareketistek;
            this.cyanid = cyanid;
            this.unit = unit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class robotdataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="robotdataResponse", Namespace="http://servis.cyanlog.com/EVAglobal6.asmx", Order=0)]
        public App19.ServiceReference1.robotdataResponseBody Body;
        
        public robotdataResponse() {
        }
        
        public robotdataResponse(App19.ServiceReference1.robotdataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servis.cyanlog.com/EVAglobal6.asmx")]
    public partial class robotdataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string robotdataResult;
        
        public robotdataResponseBody() {
        }
        
        public robotdataResponseBody(string robotdataResult) {
            this.robotdataResult = robotdataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class classctrlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="classctrl", Namespace="http://servis.cyanlog.com/EVAglobal6.asmx", Order=0)]
        public App19.ServiceReference1.classctrlRequestBody Body;
        
        public classctrlRequest() {
        }
        
        public classctrlRequest(App19.ServiceReference1.classctrlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servis.cyanlog.com/EVAglobal6.asmx")]
    public partial class classctrlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string soru;
        
        public classctrlRequestBody() {
        }
        
        public classctrlRequestBody(string soru) {
            this.soru = soru;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class classctrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="classctrlResponse", Namespace="http://servis.cyanlog.com/EVAglobal6.asmx", Order=0)]
        public App19.ServiceReference1.classctrlResponseBody Body;
        
        public classctrlResponse() {
        }
        
        public classctrlResponse(App19.ServiceReference1.classctrlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servis.cyanlog.com/EVAglobal6.asmx")]
    public partial class classctrlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string classctrlResult;
        
        public classctrlResponseBody() {
        }
        
        public classctrlResponseBody(string classctrlResult) {
            this.classctrlResult = classctrlResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EVAglobalSoapChannel : App19.ServiceReference1.EVAglobalSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EVAglobalSoapClient : System.ServiceModel.ClientBase<App19.ServiceReference1.EVAglobalSoap>, App19.ServiceReference1.EVAglobalSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EVAglobalSoapClient() : 
                base(EVAglobalSoapClient.GetDefaultBinding(), EVAglobalSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.EVAglobalSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EVAglobalSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(EVAglobalSoapClient.GetBindingForEndpoint(endpointConfiguration), EVAglobalSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EVAglobalSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EVAglobalSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EVAglobalSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EVAglobalSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EVAglobalSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<App19.ServiceReference1.servistestResponse> App19.ServiceReference1.EVAglobalSoap.servistestAsync(App19.ServiceReference1.servistestRequest request) {
            return base.Channel.servistestAsync(request);
        }
        
        public System.Threading.Tasks.Task<App19.ServiceReference1.servistestResponse> servistestAsync() {
            App19.ServiceReference1.servistestRequest inValue = new App19.ServiceReference1.servistestRequest();
            inValue.Body = new App19.ServiceReference1.servistestRequestBody();
            return ((App19.ServiceReference1.EVAglobalSoap)(this)).servistestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<App19.ServiceReference1.loginResponse> App19.ServiceReference1.EVAglobalSoap.loginAsync(App19.ServiceReference1.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<App19.ServiceReference1.loginResponse> loginAsync(string cyanid, string cyanpass) {
            App19.ServiceReference1.loginRequest inValue = new App19.ServiceReference1.loginRequest();
            inValue.Body = new App19.ServiceReference1.loginRequestBody();
            inValue.Body.cyanid = cyanid;
            inValue.Body.cyanpass = cyanpass;
            return ((App19.ServiceReference1.EVAglobalSoap)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<App19.ServiceReference1.konusResponse> App19.ServiceReference1.EVAglobalSoap.konusAsync(App19.ServiceReference1.konusRequest request) {
            return base.Channel.konusAsync(request);
        }
        
        public System.Threading.Tasks.Task<App19.ServiceReference1.konusResponse> konusAsync(string soru, string cyanid, string cyanpass, string p, string lng) {
            App19.ServiceReference1.konusRequest inValue = new App19.ServiceReference1.konusRequest();
            inValue.Body = new App19.ServiceReference1.konusRequestBody();
            inValue.Body.soru = soru;
            inValue.Body.cyanid = cyanid;
            inValue.Body.cyanpass = cyanpass;
            inValue.Body.p = p;
            inValue.Body.lng = lng;
            return ((App19.ServiceReference1.EVAglobalSoap)(this)).konusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<App19.ServiceReference1.aiResponse> App19.ServiceReference1.EVAglobalSoap.aiAsync(App19.ServiceReference1.aiRequest request) {
            return base.Channel.aiAsync(request);
        }
        
        public System.Threading.Tasks.Task<App19.ServiceReference1.aiResponse> aiAsync() {
            App19.ServiceReference1.aiRequest inValue = new App19.ServiceReference1.aiRequest();
            inValue.Body = new App19.ServiceReference1.aiRequestBody();
            return ((App19.ServiceReference1.EVAglobalSoap)(this)).aiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<App19.ServiceReference1.bekciResponse> App19.ServiceReference1.EVAglobalSoap.bekciAsync(App19.ServiceReference1.bekciRequest request) {
            return base.Channel.bekciAsync(request);
        }
        
        public System.Threading.Tasks.Task<App19.ServiceReference1.bekciResponse> bekciAsync(string sor) {
            App19.ServiceReference1.bekciRequest inValue = new App19.ServiceReference1.bekciRequest();
            inValue.Body = new App19.ServiceReference1.bekciRequestBody();
            inValue.Body.sor = sor;
            return ((App19.ServiceReference1.EVAglobalSoap)(this)).bekciAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<App19.ServiceReference1.userinfoResponse> App19.ServiceReference1.EVAglobalSoap.userinfoAsync(App19.ServiceReference1.userinfoRequest request) {
            return base.Channel.userinfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<App19.ServiceReference1.userinfoResponse> userinfoAsync(string cyanid, string cyanpass, string istek) {
            App19.ServiceReference1.userinfoRequest inValue = new App19.ServiceReference1.userinfoRequest();
            inValue.Body = new App19.ServiceReference1.userinfoRequestBody();
            inValue.Body.cyanid = cyanid;
            inValue.Body.cyanpass = cyanpass;
            inValue.Body.istek = istek;
            return ((App19.ServiceReference1.EVAglobalSoap)(this)).userinfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<App19.ServiceReference1.goruntuResponse> App19.ServiceReference1.EVAglobalSoap.goruntuAsync(App19.ServiceReference1.goruntuRequest request) {
            return base.Channel.goruntuAsync(request);
        }
        
        public System.Threading.Tasks.Task<App19.ServiceReference1.goruntuResponse> goruntuAsync(string name, string cyanid, string cyanpass, string p, string lng) {
            App19.ServiceReference1.goruntuRequest inValue = new App19.ServiceReference1.goruntuRequest();
            inValue.Body = new App19.ServiceReference1.goruntuRequestBody();
            inValue.Body.name = name;
            inValue.Body.cyanid = cyanid;
            inValue.Body.cyanpass = cyanpass;
            inValue.Body.p = p;
            inValue.Body.lng = lng;
            return ((App19.ServiceReference1.EVAglobalSoap)(this)).goruntuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<App19.ServiceReference1.ucpartiResponse> App19.ServiceReference1.EVAglobalSoap.ucpartiAsync(App19.ServiceReference1.ucpartiRequest request) {
            return base.Channel.ucpartiAsync(request);
        }
        
        public System.Threading.Tasks.Task<App19.ServiceReference1.ucpartiResponse> ucpartiAsync(string id, string cyankey) {
            App19.ServiceReference1.ucpartiRequest inValue = new App19.ServiceReference1.ucpartiRequest();
            inValue.Body = new App19.ServiceReference1.ucpartiRequestBody();
            inValue.Body.id = id;
            inValue.Body.cyankey = cyankey;
            return ((App19.ServiceReference1.EVAglobalSoap)(this)).ucpartiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<App19.ServiceReference1.robotdataResponse> App19.ServiceReference1.EVAglobalSoap.robotdataAsync(App19.ServiceReference1.robotdataRequest request) {
            return base.Channel.robotdataAsync(request);
        }
        
        public System.Threading.Tasks.Task<App19.ServiceReference1.robotdataResponse> robotdataAsync(string hareketistek, string cyanid, int unit) {
            App19.ServiceReference1.robotdataRequest inValue = new App19.ServiceReference1.robotdataRequest();
            inValue.Body = new App19.ServiceReference1.robotdataRequestBody();
            inValue.Body.hareketistek = hareketistek;
            inValue.Body.cyanid = cyanid;
            inValue.Body.unit = unit;
            return ((App19.ServiceReference1.EVAglobalSoap)(this)).robotdataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<App19.ServiceReference1.classctrlResponse> App19.ServiceReference1.EVAglobalSoap.classctrlAsync(App19.ServiceReference1.classctrlRequest request) {
            return base.Channel.classctrlAsync(request);
        }
        
        public System.Threading.Tasks.Task<App19.ServiceReference1.classctrlResponse> classctrlAsync(string soru) {
            App19.ServiceReference1.classctrlRequest inValue = new App19.ServiceReference1.classctrlRequest();
            inValue.Body = new App19.ServiceReference1.classctrlRequestBody();
            inValue.Body.soru = soru;
            return ((App19.ServiceReference1.EVAglobalSoap)(this)).classctrlAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.EVAglobalSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.EVAglobalSoap)) {
                return new System.ServiceModel.EndpointAddress("http://servis.cyanlog.com/evaglobal6.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return EVAglobalSoapClient.GetBindingForEndpoint(EndpointConfiguration.EVAglobalSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return EVAglobalSoapClient.GetEndpointAddress(EndpointConfiguration.EVAglobalSoap);
        }
        
        public enum EndpointConfiguration {
            
            EVAglobalSoap,
        }
    }
}
